name: 'action-test'
description: 'Run tests when pull-requests are opened, or commits pushed.'
author: 'Giorgio Audrito'
branding:
  icon: eye
  color: black
inputs:
  command:
    description: 'The command to run.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - './src'
    - './make.sh'
    - 'pedantic'
    - ${{ inputs.command }}
