cc_library(
    name = 'spawner',
    hdrs = ['spawner.hpp'],
    srcs = ['spawner.cpp'],
    deps = [
        "//lib:settings",
        "//lib/common:distribution",
        "//lib/common:tagged_tuple",
        "//lib/common:traits",
        "//lib/component:timer",
    ],
    visibility = [
        '//visibility:public',
    ],
)
