cc_library(
    name = 'multitype_map',
    hdrs = ['multitype_map.hpp'],
    srcs = ['multitype_map.cpp'],
    deps = [
        "//lib/util:traits",
    ],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'traits',
    hdrs = ['traits.hpp'],
    srcs = ['traits.cpp'],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'twin',
    hdrs = ['twin.hpp'],
    srcs = ['twin.cpp'],
    deps = [ ],
    visibility = [
        '//visibility:public',
    ],
)
