cc_library(
    name = 'aggregator',
    hdrs = ['aggregator.hpp'],
    srcs = ['aggregator.cpp'],
    deps = [
        "//lib/common:algorithm",
        "//lib/common:tagged_tuple",
        "//lib/common:traits",
    ],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'algorithm',
    hdrs = ['algorithm.hpp'],
    srcs = ['algorithm.cpp'],
    deps = [ ],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'distribution',
    hdrs = ['distribution.hpp'],
    srcs = ['distribution.cpp'],
    deps = [
        "//lib/common:tagged_tuple",
    ],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'flat_ptr',
    hdrs = ['flat_ptr.hpp'],
    srcs = ['flat_ptr.cpp'],
    deps = [ ],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'multitype_map',
    hdrs = ['multitype_map.hpp'],
    srcs = ['multitype_map.cpp'],
    deps = [
        "//lib/common:traits",
    ],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'mutex',
    hdrs = ['mutex.hpp'],
    srcs = ['mutex.cpp'],
    deps = [ ],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'sequence',
    hdrs = ['sequence.hpp'],
    srcs = ['sequence.cpp'],
    deps = [
        "//lib:settings",
        "//lib/common:distribution",
        "//lib/common:tagged_tuple",
        "//lib/common:traits",
    ],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'tagged_tuple',
    srcs = ['tagged_tuple.hpp'],
    deps = [
        "//lib/common:traits",
    ],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'traits',
    hdrs = ['traits.hpp'],
    srcs = ['traits.cpp'],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'twin',
    hdrs = ['twin.hpp'],
    srcs = ['twin.cpp'],
    deps = [ ],
    visibility = [
        '//visibility:public',
    ],
)
