cc_library(
    name = 'flat_ptr',
    hdrs = ['flat_ptr.hpp'],
    srcs = ['flat_ptr.cpp'],
    deps = [ ],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'multitype_map',
    hdrs = ['multitype_map.hpp'],
    srcs = ['multitype_map.cpp'],
    deps = [
        "//lib/common:traits",
    ],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'tagged_tuple',
    hdrs = ['tagged_tuple.hpp'],
    srcs = ['tagged_tuple.cpp'],
    deps = [
        "//lib/common:traits",
    ],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'traits',
    hdrs = ['traits.hpp'],
    srcs = ['traits.cpp'],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'twin',
    hdrs = ['twin.hpp'],
    srcs = ['twin.cpp'],
    deps = [ ],
    visibility = [
        '//visibility:public',
    ],
)
