cc_library(
    name = 'collection',
    hdrs = ['collection.hpp'],
    srcs = ['collection.cpp'],
    deps = [
        "//lib/coordination:utils",
    ],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'geometry',
    hdrs = ['geometry.hpp'],
    srcs = ['geometry.cpp'],
    deps = [
        "//lib/common:array",
        "//lib/coordination:utils",
    ],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'spreading',
    hdrs = ['spreading.hpp'],
    srcs = ['spreading.cpp'],
    deps = [
        "//lib/coordination:utils",
    ],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'utils',
    hdrs = ['utils.hpp'],
    srcs = ['utils.cpp'],
    deps = [
        "//lib/data:field",
        "//lib/data:trace",
    ],
    visibility = [
        '//visibility:public',
    ],
)
