cc_library(
    name = 'field',
    hdrs = ['field.hpp'],
    srcs = ['field.cpp'],
    deps = [
        "//lib:settings",
        "//lib/util:traits",
    ],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'multitype_map',
    hdrs = ['multitype_map.hpp'],
    srcs = ['multitype_map.cpp'],
    deps = [
        "//lib/util:traits",
    ],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'trace',
    hdrs = ['trace.hpp'],
    srcs = ['trace.cpp'],
    deps = [
        "//lib:settings",
    ],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'twin',
    hdrs = ['twin.hpp'],
    srcs = ['twin.cpp'],
    deps = [ ],
    visibility = [
        '//visibility:public',
    ],
)
