cc_library(
    name = 'exports',
    hdrs = ['exports.hpp'],
    srcs = ['exports.cpp'],
    deps = [
        "//lib/data:trace",
        "//lib/util:traits",
    ],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'field',
    hdrs = ['field.hpp'],
    srcs = ['field.cpp'],
    deps = [
        "//lib/settings",
        "//lib/util:traits",
    ],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'trace',
    hdrs = ['trace.hpp'],
    srcs = ['trace.cpp'],
    deps = [
        "//lib/settings",
    ],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'twin',
    hdrs = ['twin.hpp'],
    srcs = ['twin.cpp'],
    deps = [ ],
    visibility = [
        '//visibility:public',
    ],
)
