cc_library(
    name = 'field',
    hdrs = ['field.hpp'],
    srcs = ['field.cpp'],
    deps = [
        "//lib:settings",
        "//lib/common:traits",
    ],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'trace',
    hdrs = ['trace.hpp'],
    srcs = ['trace.cpp'],
    deps = [
        "//lib:settings",
    ],
    visibility = [
        '//visibility:public',
    ],
)
