cc_library(
    name = 'base',
    hdrs = ['base.hpp'],
    srcs = ['base.cpp'],
    deps = [
        "//lib:settings",
        "//lib/common:tagged_tuple",
    ],
    visibility = [
        '//visibility:public',
    ],
)
