cc_test(
    name = "algorithm",
    srcs = ["algorithm.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:algorithm",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)

cc_test(
    name = "immutable_map",
    srcs = ["immutable_map.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:immutable_map",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)

cc_test(
    name = "multitype_map",
    srcs = ["multitype_map.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:multitype_map",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)

cc_test(
    name = "mutex",
    srcs = ["mutex.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:algorithm",
        "//lib/common:mutex",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)

cc_test(
    name = "number_sequence",
    srcs = ["number_sequence.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:number_sequence",
        "//test:helper",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)

cc_test(
    name = "option",
    srcs = ["option.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:option",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)

cc_test(
    name = "ostream",
    srcs = ["ostream.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:multitype_map",
        "//lib/common:ostream",
        "//lib/common:random_access_map",
        "//lib/common:tagged_tuple",
        "//lib/data:tuple",
        "//lib/data:vec",
        "//lib/internal:context",
        "//lib/internal:flat_ptr",
        "//lib/internal:twin",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)

cc_test(
    name = "plot",
    srcs = ["plot.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:plot",
        "//lib/option:filter",
        "//test:helper",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)

cc_test(
    name = "profiler",
    srcs = ["profiler.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:profiler",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)

cc_test(
    name = "quaternion",
    srcs = ["quaternion.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:quaternion",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)

cc_test(
    name = "random_access_map",
    srcs = ["random_access_map.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:random_access_map",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)

cc_test(
    name = "serialize",
    srcs = ["serialize.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:multitype_map",
        "//lib/common:ostream",
        "//lib/common:plot",
        "//lib/common:serialize",
        "//lib/common:tagged_tuple",
        "//lib/data:bloom",
        "//lib/data:field",
        "//lib/data:hyperloglog",
        "//lib/data:tuple",
        "//lib/data:vec",
        "//lib/internal:flat_ptr",
        "//lib/option:aggregator",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)

cc_test(
    name = "tagged_tuple",
    srcs = ["tagged_tuple.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:tagged_tuple",
        "//test:helper",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)

cc_test(
    name = "traits",
    srcs = ["traits.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:traits",
        "//test:helper",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)

cc_test(
    name = "type_sequence",
    srcs = ["type_sequence.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:type_sequence",
        "//test:helper",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)
