cc_library(
    name = 'spreading',
    hdrs = ['spreading.hpp'],
    srcs = ['spreading.cpp'],
    deps = [
        "//lib/common:tagged_tuple",
        "//lib/common:traits",
        "//lib/data:field",
        "//lib/data:trace",
    ],
    visibility = [
        '//visibility:public',
    ],
)
