cc_test(
    name = "aggregator",
    srcs = ["aggregator.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:aggregator",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)

cc_test(
    name = "algorithm",
    srcs = ["algorithm.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:algorithm",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)

cc_test(
    name = "array",
    srcs = ["array.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:array",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)

cc_test(
    name = "distribution",
    srcs = ["distribution.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:distribution",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)

cc_test(
    name = "flat_ptr",
    srcs = ["flat_ptr.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:flat_ptr",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)

cc_test(
    name = "multitype_map",
    srcs = ["multitype_map.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:multitype_map",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)

cc_test(
    name = "mutex",
    srcs = ["mutex.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:algorithm",
        "//lib/common:mutex",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)

cc_test(
    name = "random_access_map",
    srcs = ["random_access_map.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:random_access_map",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)

cc_test(
    name = "sequence",
    srcs = ["sequence.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:distribution",
        "//lib/common:sequence",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)

cc_test(
    name = "tagged_tuple",
    srcs = ["tagged_tuple.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:tagged_tuple",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)

cc_test(
    name = "traits",
    srcs = ["traits.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:traits",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)

cc_test(
    name = "twin",
    srcs = ["twin.cpp"],
    deps = [
        "@gtest//:main",
        "//lib/common:twin",
    ],
    copts = ['-Iexternal/gtest/googletest/include/'],
    args = ['--gtest_color=yes'],
    timeout = 'short',
)
