cc_library(
    name = 'field',
    hdrs = ['field.hpp'],
    srcs = ['field.cpp'],
    deps = [
        "//lib:settings",
        "//lib/common:traits",
        "//lib/data:tuple",
    ],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'tuple',
    hdrs = ['tuple.hpp'],
    srcs = ['tuple.cpp'],
    deps = [
        "//lib/common:traits",
    ],
    visibility = [
        '//visibility:public',
    ],
)

cc_library(
    name = 'vec',
    hdrs = ['vec.hpp'],
    srcs = ['vec.cpp'],
    deps = [
    ],
    visibility = [
        '//visibility:public',
    ],
)
