name: CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository...
        uses: actions/checkout@v3
      - name: Run tests...
        uses: ./.github/action-test
      - name: Setting up node.js...
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Installing surge...
        run: npm install -g surge
      - name: Deploy documentation...
        run: surge './src/doc/html' 'fcpp-doc.surge.sh' --token ${{ secrets.SURGE_TOKEN }}
