cc_library(
    name = 'device',
    hdrs = ['device.hpp'],
    srcs = ['device.cpp'],
    deps = [
        "//lib/common:multitype_map",
        "//lib/common:traits",
        "//lib/common:twin",
        "//lib/data:context",
        "//lib/data:field",
        "//lib/data:trace",
    ],
    visibility = [
        '//visibility:public',
    ],
)
